{
    "bnf" : {
        "PT_TRANSLATION_UNIT" : [
            ["PT_EXTERNAL_DECLARATION"],
            ["PT_TRANSLATION_UNIT PT_EXTERNAL_DECLARATION"]
        ],
        "PT_EXTERNAL_DECLARATION" : [
            ["PT_FUNCTION_DEFINITION"],
            ["PT_DECLARATION"]
        ],
        "PT_PRIMARY_EXPRESSION" : [
            ["CT_IDENTIFIER"],
            ["CT_CONSTANT"],
            ["CT_STRING_LITERAL"],
            ["CT_OPEN_PAREN PT_EXPRESSION CT_CLOSE_PAREN"]
        ],
        "PT_POSTFIX_EXPRESSION" : [
            ["PT_PRIMARY_EXPRESSION"],
            ["PT_POSTFIX_EXPRESSION CT_OPEN_BRACKET PT_EXPRESSION CT_CLOSE_BRACKET"],
            ["PT_POSTFIX_EXPRESSION CT_OPEN_BRACE CT_CLOSE_BRACE"],
            ["PT_POSTFIX_EXPRESSION CT_OPEN_BRACE PT_ARGUMENT_EXPRESSION_LIST CT_CLOSE_BRACE"],
            ["PT_POSTFIX_EXPRESSION CT_DOT CT_IDENTIFIER"],
            ["PT_POSTFIX_EXPRESSION CT_PTR_OP CT_IDENTIFIER"],
            ["PT_POSTFIX_EXPRESSION CT_INC_OP"],
            ["PT_POSTFIX_EXPRESSION CT_DEC_OP"]
        ],
        "PT_ARGUMENT_EXPRESSION_LIST" : [
            ["PT_ASSIGNMENT_EXPRESSION"],
            ["PT_ARGUMENT_EXPRESSION_LIST CT_COMMA PT_ASSIGNMENT_EXPRESSION"]
        ],
        "PT_UNARY_EXPRESSION" : [
            ["PT_POSTFIX_EXPRESSION"],
            ["CT_INC_OP PT_UNARY_EXPRESSION"],
            ["CT_DEC_OP PT_UNARY_EXPRESSION"],
            ["PT_UNARY_OPERATOR PT_CAST_EXPRESSION"],
            ["CT_SIZEOF PT_UNARY_EXPRESSION"],
            ["CT_SIZEOF CT_OPEN_BRACE PT_TYPE_NAME CT_CLOSE_BRACE"]
        ],
        "PT_UNARY_OPERATOR" : [
            ["CT_AMPERSAND"],
            ["CT_STAR"],
            ["CT_ADD"],
            ["CT_SUB"],
            ["CT_TILDE"],
            ["CT_EXCLAM"]
        ],
        "PT_CAST_EXPRESSION" : [
            ["PT_UNARY_EXPRESSION"],
            ["CT_OPEN_PAREN PT_TYPE_NAME CT_CLOSE_PAREN PT_CAST_EXPRESSION"]
        ],
        "PT_MULTIPLICATIVE_EXPRESSION" : [
            ["PT_CAST_EXPRESSION"],
            ["PT_MULTIPLICATIVE_EXPRESSION CT_STAR PT_CAST_EXPRESSION"],
            ["PT_MULTIPLICATIVE_EXPRESSION CT_DIV PT_CAST_EXPRESSION"],
            ["PT_MULTIPLICATIVE_EXPRESSION CT_PERCENT PT_CAST_EXPRESSION"]
        ],
        "PT_ADDITIVE_EXPRESSION" : [
            ["PT_MULTIPLICATIVE_EXPRESSION"],
            ["PT_ADDITIVE_EXPRESSION CT_ADD PT_MULTIPLICATIVE_EXPRESSION"],
            ["PT_ADDITIVE_EXPRESSION CT_SUB PT_MULTIPLICATIVE_EXPRESSION"]
        ],
        "PT_SHIFT_EXPRESSION" : [
            ["PT_ADDITIVE_EXPRESSION"],
            ["PT_SHIFT_EXPRESSION CT_LEFT_OP PT_ADDITIVE_EXPRESSION"],
            ["PT_SHIFT_EXPRESSION CT_RIGHT_OP PT_ADDITIVE_EXPRESSION"]
        ],
        "PT_RELATIONAL_EXPRESSION" : [
            ["PT_SHIFT_EXPRESSION"],
            ["PT_RELATIONAL_EXPRESSION CT_LESS PT_SHIFT_EXPRESSION"],
            ["PT_RELATIONAL_EXPRESSION CT_GREATER PT_SHIFT_EXPRESSION"],
            ["PT_RELATIONAL_EXPRESSION CT_LE_OP PT_SHIFT_EXPRESSION"],
            ["PT_RELATIONAL_EXPRESSION CT_GE_OP PT_SHIFT_EXPRESSION"]
        ],
        "PT_EQUALITY_EXPRESSION" : [
            ["PT_RELATIONAL_EXPRESSION"],
            ["PT_EQUALITY_EXPRESSION CT_EQ_OP PT_RELATIONAL_EXPRESSION"],
            ["PT_EQUALITY_EXPRESSION CT_NE_OP PT_RELATIONAL_EXPRESSION"]
        ],
        "PT_AND_EXPRESSION" : [
            ["PT_EQUALITY_EXPRESSION"],
            ["PT_AND_EXPRESSION CT_AMPERSAND PT_EQUALITY_EXPRESSION"]
        ],
        "PT_EXCLUSIVE_OR_EXPRESSION" : [
            ["PT_AND_EXPRESSION"],
            ["PT_EXCLUSIVE_OR_EXPRESSION CT_CARET PT_AND_EXPRESSION"]
        ],
        "PT_INCLUSIVE_OR_EXPRESSION" : [
            ["PT_EXCLUSIVE_OR_EXPRESSION"],
            ["PT_INCLUSIVE_OR_EXPRESSION CT_BAR PT_EXCLUSIVE_OR_EXPRESSION"]
        ],
        "PT_LOGICAL_AND_EXPRESSION" : [
            ["PT_INCLUSIVE_OR_EXPRESSION"],
            ["PT_LOGICAL_AND_EXPRESSION CT_AND_OP PT_INCLUSIVE_OR_EXPRESSION"]
        ],
        "PT_LOGICAL_OR_EXPRESSION" : [
            ["PT_LOGICAL_AND_EXPRESSION"],
            ["PT_LOGICAL_OR_EXPRESSION CT_OR_OP PT_LOGICAL_AND_EXPRESSION"]
        ],
        "PT_CONDITIONAL_EXPRESSION" : [
            ["PT_LOGICAL_OR_EXPRESSION"],
            ["PT_LOGICAL_OR_EXPRESSION CT_QUESTION PT_EXPRESSION CT_COLON PT_CONDITIONAL_EXPRESSION"]
        ],
        "PT_ASSIGNMENT_EXPRESSION" : [
            ["PT_CONDITIONAL_EXPRESSION"],
            ["PT_UNARY_EXPRESSION PT_ASSIGNMENT_OPERATOR PT_ASSIGNMENT_EXPRESSION"]
        ],
        "PT_ASSIGNMENT_OPERATOR" : [
            ["CT_ASSIGN"],
            ["CT_MUL_ASSIGN"],
            ["CT_DIV_ASSIGN"],
            ["CT_MOD_ASSIGN"],
            ["CT_ADD_ASSIGN"],
            ["CT_SUB_ASSIGN"],
            ["CT_LEFT_ASSIGN"],
            ["CT_RIGHT_ASSIGN"],
            ["CT_AND_ASSIGN"],
            ["CT_XOR_ASSIGN"],
            ["CT_OR_ASSIGN"]
        ],
        "PT_EXPRESSION" : [
            ["PT_ASSIGNMENT_EXPRESSION"],
            ["PT_EXPRESSION CT_COMMA PT_ASSIGNMENT_EXPRESSION"]
        ],
        "PT_CONSTANT_EXPRESSION" : [
            ["PT_CONDITIONAL_EXPRESSION"]
        ],
        "PT_DECLARATION" : [
            ["PT_DECLARATION_SPECIFIERS CT_SEMICOLON"],
            ["PT_DECLARATION_SPECIFIERS PT_INIT_DECLARATOR_LIST CT_SEMICOLON"]
        ],
        "PT_DECLARATION_SPECIFIERS" : [
            ["PT_STORAGE_CLASS_SPECIFIER"],
            ["PT_STORAGE_CLASS_SPECIFIER PT_DECLARATION_SPECIFIERS"],
            ["PT_TYPE_SPECIFIER"],
            ["PT_TYPE_SPECIFIER PT_DECLARATION_SPECIFIERS"],
            ["PT_TYPE_QUALIFIER"],
            ["PT_TYPE_QUALIFIER PT_DECLARATION_SPECIFIERS"]
        ],
        "PT_INIT_DECLARATOR_LIST" : [
            ["PT_INIT_DECLARATOR"],
            ["PT_INIT_DECLARATOR_LIST CT_COMMA PT_INIT_DECLARATOR"]
        ],
        "PT_INIT_DECLARATOR" : [
            ["PT_DECLARATOR"],
            ["PT_DECLARATOR CT_ASSIGN PT_INITIALIZER"]
        ],
        "PT_STORAGE_CLASS_SPECIFIER" : [
            ["CT_TYPEDEF"],
            ["CT_EXTERN"],
            ["CT_STATIC"],
            ["CT_AUTO"],
            ["CT_REGISTER"]
        ],
        "PT_TYPE_SPECIFIER" : [
            ["CT_VOID"],
            ["CT_CHAR"],
            ["CT_SHORT"],
            ["CT_INT"],
            ["CT_LONG"],
            ["CT_FLOAT"],
            ["CT_DOUBLE"],
            ["CT_SIGNED"],
            ["CT_UNSIGNED"],
            ["PT_STRUCT_OR_UNION_SPECIFIER"],
            ["PT_ENUM_SPECIFIER"],
            ["PT_TYPE_NAME"]
        ],
        "PT_STRUCT_OR_UNION_SPECIFIER" : [
            ["PT_STRUCT_OR_UNION CT_IDENTIFIER CT_OPEN_BRACE PT_STRUCT_DECLARATION_LIST CT_CLOSE_BRACE"],
            ["PT_STRUCT_OR_UNION CT_OPEN_BRACE PT_STRUCT_DECLARATION_LIST CT_CLOSE_BRACE"],
            ["PT_STRUCT_OR_UNION CT_IDENTIFIER"]
        ],
        "PT_STRUCT_OR_UNION" : [
            ["CT_STRUCT"],
            ["CT_UNION"]
        ],
        "PT_STRUCT_DECLARATION_LIST" : [
            ["PT_STRUCT_DECLARATION"],
            ["PT_STRUCT_DECLARATION_LIST PT_STRUCT_DECLARATION"]
        ],
        "PT_STRUCT_DECLARATION" : [
            ["PT_SPECIFIER_QUALIFIER_LIST PT_STRUCT_DECLARATOR_LIST CT_SEMICOLON"]
        ],
        "PT_SPECIFIER_QUALIFIER_LIST" : [
            ["PT_TYPE_SPECIFIER PT_SPECIFIER_QUALIFIER_LIST"],
            ["PT_TYPE_SPECIFIER"],
            ["PT_TYPE_QUALIFIER PT_SPECIFIER_QUALIFIER_LIST"],
            ["PT_TYPE_QUALIFIER"]
        ],
        "PT_STRUCT_DECLARATOR_LIST" : [
            ["PT_STRUCT_DECLARATOR"],
            ["PT_STRUCT_DECLARATOR_LIST CT_COMMA PT_STRUCT_DECLARATOR"]
        ],
        "PT_STRUCT_DECLARATOR" : [
            ["PT_DECLARATOR"],
            ["CT_COLON PT_CONSTANT_EXPRESSION"],
            ["PT_DECLARATOR CT_COLON PT_CONSTANT_EXPRESSION"]
        ],
        "PT_ENUM_SPECIFIER" : [
            ["CT_ENUM CT_OPEN_BRACE PT_ENUMERATOR_LIST CT_CLOSE_BRACE"],
            ["CT_ENUM CT_IDENTIFIER CT_OPEN_BRACE PT_ENUMERATOR_LIST CT_CLOSE_BRACE"],
            ["CT_ENUM CT_IDENTIFIER"]
        ],
        "PT_ENUMERATOR_LIST" : [
            ["PT_ENUMERATOR"],
            ["PT_ENUMERATOR_LIST CT_COMMA PT_ENUMERATOR"]
        ],
        "PT_ENUMERATOR" : [
            ["CT_IDENTIFIER"],
            ["CT_IDENTIFIER CT_ASSIGN PT_CONSTANT_EXPRESSION"]
        ],
        "PT_TYPE_QUALIFIER" : [
            ["CT_CONST"],
            ["CT_VOLATILE"]
        ],
        "PT_DECLARATOR" : [
            ["PT_POINTER PT_DIRECT_DECLARATOR"],
            ["PT_DIRECT_DECLARATOR"]
        ],
        "PT_DIRECT_DECLARATOR" : [
            ["CT_IDENTIFIER"],
            ["CT_OPEN_PAREN PT_DECLARATOR CT_CLOSE_PAREN"],
            ["PT_DIRECT_DECLARATOR CT_OPEN_BRACKET PT_CONSTANT_EXPRESSION CT_CLOSE_BRACKET"],
            ["PT_DIRECT_DECLARATOR CT_OPEN_BRACKET CT_CLOSE_BRACKET"],
            ["PT_DIRECT_DECLARATOR CT_OPEN_PAREN PT_PARAMETER_TYPE_LIST CT_CLOSE_PAREN"],
            ["PT_DIRECT_DECLARATOR CT_OPEN_PAREN PT_IDENTIFIER_LIST CT_CLOSE_PAREN"],
            ["PT_DIRECT_DECLARATOR CT_OPEN_PAREN CT_CLOSE_PAREN"]
        ],
        "PT_POINTER" : [
            ["CT_STAR"],
            ["CT_STAR PT_TYPE_QUALIFIER_LIST"],
            ["CT_STAR PT_POINTER"],
            ["CT_STAR PT_TYPE_QUALIFIER PT_POINTER"]
        ],
        "PT_TYPE_QUALIFIER_LIST" : [
            ["PT_TYPE_QUALIFIER"],
            ["PT_TYPE_QUALIFIER_LIST PT_TYPE_QUALIFIER"]
        ],
        "PT_PARAMETER_TYPE_LIST" : [
            ["PT_PARAMETER_LIST"],
            ["PT_PARAMETER_LIST CT_COMMA CT_ELLIPSIS"]
        ],
        "PT_PARAMETER_LIST" : [
            ["PT_PARAMETER_DECLARATION"],
            ["PT_PARAMETER_LIST CT_COMMA PT_PARAMETER_DECLARATION"]
        ],
        "PT_PARAMETER_DECLARATION" : [
            ["PT_DECLARATION_SPECIFIERS PT_DECLARATOR"],
            ["PT_DECLARATION_SPECIFIERS PT_ABSTRACT_DECLARATOR"],
            ["PT_DECLARATION_SPECIFIERS"]
        ],
        "PT_IDENTIFIER_LIST" : [
            ["CT_IDENTIFIER"],
            ["PT_IDENTIFIER_LIST CT_COMMA CT_IDENTIFIER"]
        ],
        "PT_TYPE_NAME" : [
            ["PT_SPECIFIER_QUALIFIER_LIST"],
            ["PT_SPECIFIER_QUALIFIER_LIST PT_ABSTRACT_DECLARATOR"]
        ],
        "PT_ABSTRACT_DECLARATOR" : [
            ["PT_POINTER"],
            ["PT_DIRECT_ABSTRACT_DECLARATOR"],
            ["PT_POINTER PT_DIRECT_DECLARATOR"]
        ],
        "PT_DIRECT_ABSTRACT_DECLARATOR" : [
            ["CT_OPEN_PAREN PT_ABSTRACT_DECLARATOR CT_CLOSE_PAREN"],
            ["CT_OPEN_BRACKET CT_CLOSE_BRACKET"],
            ["CT_OPEN_BRACKET PT_CONSTANT_EXPRESSION CT_CLOSE_BRACKET"],
            ["PT_DIRECT_ABSTRACT_DECLARATOR CT_OPEN_BRACKET CT_CLOSE_BRACKET"],
            ["PT_DIRECT_ABSTRACT_DECLARATOR CT_OPEN_BRACKET PT_CONSTANT_EXPRESSION CT_CLOSE_BRACKET"],
            ["CT_OPEN_PAREN CT_CLOSE_PAREN"],
            ["CT_OPEN_PAREN PT_PARAMETER_TYPE_LIST CT_CLOSE_PAREN"],
            ["PT_DIRECT_ABSTRACT_DECLARATOR CT_OPEN_PAREN CT_CLOSE_PAREN"],
            ["PT_DIRECT_ABSTRACT_DECLARATOR CT_OPEN_PAREN PT_PARAMETER_TYPE_LIST CT_CLOSE_PAREN"]
        ],
        "PT_INITIALIZER" : [
            ["PT_ASSIGNMENT_EXPRESSION"],
            ["CT_OPEN_BRACE PT_INITIALIZER_LIST CT_CLOSE_BRACE"],
            ["CT_OPEN_BRACE PT_INITIALIZER_LIST CT_COMMA CT_CLOSE_BRACE"]
        ],
        "PT_INITIALIZER_LIST" : [
            ["PT_INITIALIZER"],
            ["PT_INITIALIZER_LIST CT_COMMA CT_IDENTIFIER"]
        ],
        "PT_STATEMENT" : [
            ["PT_LABELED_STATEMENT"],
            ["PT_COMPOUND_STATEMENT"],
            ["PT_EXPRESSION_STATEMENT"],
            ["PT_SELECTION_STATEMENT"],
            ["PT_ITERATION_STATEMENT"],
            ["PT_JUMP_STATEMENT"]
        ],
        "PT_LABELED_STATEMENT" : [
            ["CT_IDENTIFIER CT_COLON PT_STATEMENT"],
            ["CT_CASE PT_CONSTANT_EXPRESSION CT_COLON PT_STATEMENT"],
            ["CT_DEFAULT CT_COLON PT_STATEMENT"]
        ],
        "PT_COMPOUND_STATEMENT" : [
            ["CT_OPEN_BRACE CT_CLOSE_BRACE"],
            ["CT_OPEN_BRACE PT_STATEMENT_LIST CT_CLOSE_BRACE"],
            ["CT_OPEN_BRACE PT_DECLARATION_LIST CT_CLOSE_BRACE"],
            ["CT_OPEN_BRACE PT_DECLARATION_LIST PT_STATEMENT_LIST CT_CLOSE_BRACE"]
        ],
        "PT_DECLARATION_LIST" : [
            ["PT_DECLARATION"],
            ["PT_DECLARATION_LIST PT_DECLARATION"]
        ],
        "PT_STATEMENT_LIST" : [
            ["PT_STATEMENT"],
            ["PT_STATEMENT_LIST PT_STATEMENT"]
        ],
        "PT_EXPRESSION_STATEMENT" : [
            ["CT_SEMICOLON"],
            ["PT_EXPRESSION CT_SEMICOLON"]
        ],
        "PT_SELECTION_STATEMENT" : [
            ["CT_IF CT_OPEN_PAREN PT_EXPRESSION CT_CLOSE_PAREN PT_STATEMENT"],
            ["CT_IF CT_OPEN_PAREN PT_EXPRESSION CT_CLOSE_PAREN PT_STATEMENT CT_ELSE PT_STATEMENT"],
            ["CT_SWITCH CT_OPEN_PAREN PT_EXPRESSION CT_CLOSE_PAREN PT_STATEMENT"]
        ],
        "PT_ITERATION_STATEMENT" : [
            ["CT_WHILE CT_OPEN_PAREN PT_EXPRESSION CT_CLOSE_PAREN PT_STATEMENT"],
            ["CT_DO PT_STATEMENT CT_WHILE CT_OPEN_PAREN PT_EXPRESSION CT_CLOSE_PAREN"],
            ["CT_FOR CT_OPEN_PAREN PT_EXPRESSION_STATEMENT PT_EXPRESSION_STATEMENT CT_CLOSE_PAREN PT_STATEMENT"],
            ["CT_FOR CT_OPEN_PAREN PT_EXPRESSION_STATEMENT PT_EXPRESSION_STATEMENT PT_EXPRESSION CT_CLOSE_PAREN PT_STATEMENT"]
        ],
        "PT_JUMP_STATEMENT" : [
            ["CT_GOTO CT_IDENTIFIER CT_SEMICOLON"],
            ["CT_CONTINUE CT_SEMICOLON"],
            ["CT_BREAK CT_SEMICOLON"],
            ["CT_RETURN CT_SEMICOLON"],
            ["CT_RETURN PT_EXPRESSION CT_SEMICOLON"]
        ],
        "PT_FUNCTION_DEFINITION" : [
            ["PT_DECLARATION_SPECIFIERS PT_DECLARATOR PT_DECLARATION_LIST PT_COMPOUND_STATEMENT"],
            ["PT_DECLARATION_SPECIFIERS PT_DECLARATOR PT_COMPOUND_STATEMENT"],
            ["PT_DECLARATOR PT_DECLARATION_LIST PT_COMPOUND_STATEMENT"],
            ["PT_DECLARATOR PT_COMPOUND_STATEMENT"]
        ]
    }
}
